### ISSUE TITLE
Listener has 0 arguments but it needs at least 1 to match the given value classes.

### ISSUE THREAD

**Issue by ruprict** [evan-liu/as3-signals-utilities-async#1]
I am getting this error when I try to do 

`Async.proceedOnEvent(this,instance,SignalAsyncEvent.CALLED,500, handleStadiumsRecieved);`

All of the params to proceedOnEvent seem right to me.  instance is my Signal class:

`new StadiumsRecievedSignal(Stadiums);`

And the handler is:
`private function handleStadiumsRecieved(event:SignalAsyncEvent,...rest):void{
    assertThat(event.args[0].items.length,equalTo(2));
}`

Any idea what I am doing wrong?

Oh, and sorry if this is the wrong place to put a question.

Ruprict

**Comment by ruprict** [comment]
So, under further investigation, this seems to happen when the Signal has a payload.  Above, StaiumsRecievedSignal has a value object of Stadiums.  Does the async stuff handle this in a special way?

**Comment by evan-liu** [comment]
It's fixed now, please try again :)
