### ISSUE TITLE
Do not include as3-signals library in exported swc

### ISSUE THREAD

**Issue by cef62** [evan-liu/as3-signals-utilities-async#3]
Please do not include originel as3-signals source code into compiled swc of as3-signals-utilities-async. Include it as external library so we can use our as3-signals swc or source code without errors. 

In any case very useful library! 
Thank for sharing it!

I've modified your build.xml in this way:

<taskdef resource="flexTasks.tasks" classpath="${FLEX_HOME}/ant/lib/flexTasks.jar" />
<target name="swc" depends="" description="Compile AS3 code into a SWC">
        <compc keep-generated-actionscript="false" output="${output.swc}" incremental="true">
            <source-path path-element="${FLEX_HOME}/frameworks"/>
            <external-library-path dir="${libs.dir}" append="true">
                <include name="flexunit.swc" />
                <include name="as3-signals-v0.6.swc" />
            </external-library-path>
            <include-sources  dir="${src.dir}/${package.dir}" includes="*"/>
            <load-config filename="${FLEX_HOME}/frameworks/flex-config.xml"/>
        </compc>
    </target>

**Comment by evan-liu** [comment]
updated. Thanks very much for your xml.
